
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IJTilbe
 */
public class AbcGui extends javax.swing.JFrame {

    /**
     * Creates new form AbcGui
     */
    
    int STUDENT = 1;
    int TEACHER = 2;
    int choice = 0;
    int total = 0;
    int tuition = 0;
    
    
    public AbcGui() {
        initComponents();
        menuBar.setVisible(false);
        mainPanel.setVisible(false);
        setAllInvisible();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentViewBG = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        logoHome = new javax.swing.JLabel();
        newPanel = new javax.swing.JPanel();
        teacherDetailsFrame = new javax.swing.JInternalFrame();
        teacherDetailsName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        deptCB = new javax.swing.JComboBox<>();
        desigCB = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        teacherDetailsBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phoneTF1 = new javax.swing.JTextField();
        fnameTF1 = new javax.swing.JTextField();
        lnameTF1 = new javax.swing.JTextField();
        addressTF1 = new javax.swing.JTextField();
        newBtn = new javax.swing.JButton();
        genderCB1 = new javax.swing.JComboBox<>();
        addHeaderLabel = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        updateSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        fnameTF = new javax.swing.JTextField();
        lnameTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        genderCB = new javax.swing.JComboBox<>();
        updateID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        updateHeaderLabel = new javax.swing.JLabel();
        updateCancelBtn = new javax.swing.JButton();
        deletePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        delTF = new javax.swing.JTextField();
        delBtn = new javax.swing.JButton();
        delLabel = new javax.swing.JLabel();
        viewStudentPanel = new javax.swing.JPanel();
        viewStudentLabel = new javax.swing.JLabel();
        withRB = new javax.swing.JRadioButton();
        withoutRB = new javax.swing.JRadioButton();
        allRB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        viewTeacherPanel = new javax.swing.JPanel();
        viewTeacherLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        enlistPanel = new javax.swing.JPanel();
        enlistSearch = new javax.swing.JLabel();
        enlistID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        delLabel1 = new javax.swing.JLabel();
        enlistPanel2 = new javax.swing.JPanel();
        nameEnlistLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        newModuleSpinner = new javax.swing.JSpinner();
        repModuleSpinner = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        tuitionLbl = new javax.swing.JLabel();
        enrollBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        depositTF = new javax.swing.JTextField();
        loginPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        abcLogoLogin = new javax.swing.JLabel();
        pwLabel = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        pwTF = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        studentMenu = new javax.swing.JMenu();
        newStudent = new javax.swing.JMenuItem();
        updateStudent = new javax.swing.JMenuItem();
        enlistStudent = new javax.swing.JMenuItem();
        deleteStudent = new javax.swing.JMenuItem();
        showBalance = new javax.swing.JMenuItem();
        viewStudent = new javax.swing.JMenuItem();
        teacherMenu = new javax.swing.JMenu();
        newTeacher = new javax.swing.JMenuItem();
        updateTeacher = new javax.swing.JMenuItem();
        deleteTeacher = new javax.swing.JMenuItem();
        salaryTeacher = new javax.swing.JMenuItem();
        viewTeacher = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABC College");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(242, 250, 250));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("abcFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        mainPanel.setRequestFocusEnabled(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logoHome.setFocusable(false);
        logoHome.setRequestFocusEnabled(false);
        logoHome.setVerifyInputWhenFocusTarget(false);
        homePanel.add(logoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        mainPanel.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        newPanel.setBackground(new java.awt.Color(255, 255, 255));
        newPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherDetailsFrame.setTitle("Teacher Details");
        teacherDetailsFrame.setToolTipText("");
        teacherDetailsFrame.setFrameIcon(null);
        teacherDetailsFrame.setInheritsPopupMenu(true);
        try {
            teacherDetailsFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        teacherDetailsFrame.setVisible(false);
        teacherDetailsFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherDetailsName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        teacherDetailsFrame.getContentPane().add(teacherDetailsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel16.setText("Department");
        teacherDetailsFrame.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        deptCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "Computing" }));
        teacherDetailsFrame.getContentPane().add(deptCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 170, -1));

        desigCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Coordinator", "Head of Faculty" }));
        teacherDetailsFrame.getContentPane().add(desigCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, -1));

        jLabel17.setText("Designation");
        teacherDetailsFrame.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        teacherDetailsBtn.setText("Add Teacher");
        teacherDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherDetailsBtnActionPerformed(evt);
            }
        });
        teacherDetailsFrame.getContentPane().add(teacherDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 30));

        newPanel.add(teacherDetailsFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 300, 300));

        jLabel6.setText("First Name");
        newPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 57, -1, -1));

        jLabel7.setText("Last Name");
        newPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 129, -1, -1));

        jLabel8.setText("Gender");
        newPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 194, -1, -1));

        jLabel9.setText("Phone Number");
        newPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 194, -1, -1));

        jLabel10.setText("Address");
        newPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 259, -1, -1));
        newPanel.add(phoneTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 214, 171, 34));

        fnameTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTF1ActionPerformed(evt);
            }
        });
        newPanel.add(fnameTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 77, 279, 34));
        newPanel.add(lnameTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 149, 279, 34));
        newPanel.add(addressTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 279, 279, 66));

        newBtn.setText("Submit");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        newPanel.add(newBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 363, -1, 30));

        genderCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "M", "F" }));
        genderCB1.setOpaque(false);
        genderCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderCB1ActionPerformed(evt);
            }
        });
        newPanel.add(genderCB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 214, 90, 34));
        newPanel.add(addHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, 20));

        mainPanel.add(newPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        updatePanel.setBackground(new java.awt.Color(255, 255, 255));
        updatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        updateSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateSearchMouseClicked(evt);
            }
        });
        updatePanel.add(updateSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 40, 40));

        jLabel1.setText("First Name");
        updatePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel2.setText("Last Name");
        updatePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel3.setText("Gender");
        updatePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel4.setText("Phone Number");
        updatePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel5.setText("Address");
        updatePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        phoneTF.setEnabled(false);
        updatePanel.add(phoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 171, 34));

        fnameTF.setEnabled(false);
        fnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTFActionPerformed(evt);
            }
        });
        updatePanel.add(fnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 279, 34));

        lnameTF.setEnabled(false);
        updatePanel.add(lnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 279, 34));

        addressTF.setEnabled(false);
        updatePanel.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 279, 66));

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        updatePanel.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 120, 30));

        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "M", "F" }));
        genderCB.setEnabled(false);
        genderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderCBActionPerformed(evt);
            }
        });
        updatePanel.add(genderCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 100, 34));
        updatePanel.add(updateID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 240, 40));

        jLabel11.setText("ID");
        updatePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 20, 20));

        updateHeaderLabel.setText("Update");
        updatePanel.add(updateHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        updateCancelBtn.setText("Cancel");
        updateCancelBtn.setEnabled(false);
        updateCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCancelBtnActionPerformed(evt);
            }
        });
        updatePanel.add(updateCancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 120, 30));

        mainPanel.add(updatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        deletePanel.setBackground(new java.awt.Color(255, 255, 255));
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Enter ID:");
        deletePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 60, 20));

        delTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        delTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delTFActionPerformed(evt);
            }
        });
        deletePanel.add(delTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 250, 40));

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        deletePanel.add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, 30));

        delLabel.setText("Delete");
        deletePanel.add(delLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        mainPanel.add(deletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        viewStudentPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewStudentLabel.setText("View Student");
        viewStudentPanel.add(viewStudentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        studentViewBG.add(withRB);
        withRB.setText("With balance");
        withRB.setContentAreaFilled(false);
        withRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withRBActionPerformed(evt);
            }
        });
        viewStudentPanel.add(withRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        studentViewBG.add(withoutRB);
        withoutRB.setText("Without Balance");
        withoutRB.setContentAreaFilled(false);
        withoutRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withoutRBActionPerformed(evt);
            }
        });
        viewStudentPanel.add(withoutRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        studentViewBG.add(allRB);
        allRB.setSelected(true);
        allRB.setText("View All");
        allRB.setContentAreaFilled(false);
        allRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRBActionPerformed(evt);
            }
        });
        viewStudentPanel.add(allRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        studentTable.setToolTipText("");
        studentTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        studentTable.setAutoscrolls(false);
        studentTable.setFillsViewportHeight(true);
        studentTable.setFocusable(false);
        studentTable.setGridColor(new java.awt.Color(102, 102, 102));
        studentTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(studentTable);

        viewStudentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 640, 320));

        mainPanel.add(viewStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        viewTeacherPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewTeacherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewTeacherLabel.setText("View Teacher");
        viewTeacherPanel.add(viewTeacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        teacherTable.setToolTipText("");
        teacherTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        teacherTable.setAutoscrolls(false);
        teacherTable.setFillsViewportHeight(true);
        teacherTable.setFocusable(false);
        teacherTable.setGridColor(new java.awt.Color(102, 102, 102));
        teacherTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(teacherTable);

        viewTeacherPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 640, 320));

        mainPanel.add(viewTeacherPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        enlistPanel.setBackground(new java.awt.Color(255, 255, 255));
        enlistPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enlistSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        enlistSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enlistSearchMouseClicked(evt);
            }
        });
        enlistPanel.add(enlistSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 40, 40));

        enlistID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enlistID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        enlistID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enlistIDMouseClicked(evt);
            }
        });
        enlistID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enlistIDActionPerformed(evt);
            }
        });
        enlistPanel.add(enlistID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 200, 40));

        jLabel14.setText("Enter ID:");
        enlistPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 60, 20));

        delLabel1.setText("Student Enrollment");
        enlistPanel.add(delLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        enlistPanel2.setBackground(new java.awt.Color(255, 255, 255));
        enlistPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        enlistPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameEnlistLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enlistPanel2.add(nameEnlistLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel12.setText("Repeat Modules");
        enlistPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel15.setText("New Modules");
        enlistPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        newModuleSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newModuleSpinnerStateChanged(evt);
            }
        });
        enlistPanel2.add(newModuleSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, 30));

        repModuleSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                repModuleSpinnerStateChanged(evt);
            }
        });
        enlistPanel2.add(repModuleSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 70, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Tuition Fee");
        enlistPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        tuitionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tuitionLbl.setForeground(new java.awt.Color(102, 0, 0));
        enlistPanel2.add(tuitionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        enrollBtn.setText("Enroll");
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });
        enlistPanel2.add(enrollBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 80, 30));
        enlistPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, 500, 20));

        jLabel19.setText("Deposit Amount");
        enlistPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        depositTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositTFActionPerformed(evt);
            }
        });
        enlistPanel2.add(depositTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 120, 30));

        enlistPanel.add(enlistPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 500, 290));

        mainPanel.add(enlistPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginPanel.setFocusable(false);
        loginPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        loginPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        loginPanel.setOpaque(false);
        loginPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        loginPanel.setRequestFocusEnabled(false);
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel.setText("Username");
        loginPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, 10));

        abcLogoLogin.setBackground(new java.awt.Color(255, 255, 255));
        abcLogoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abcLogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abclogo.jpg"))); // NOI18N
        abcLogoLogin.setMaximumSize(new java.awt.Dimension(570, 200));
        abcLogoLogin.setMinimumSize(new java.awt.Dimension(570, 200));
        abcLogoLogin.setOpaque(true);
        abcLogoLogin.setPreferredSize(new java.awt.Dimension(570, 200));
        abcLogoLogin.setRequestFocusEnabled(false);
        abcLogoLogin.setVerifyInputWhenFocusTarget(false);
        loginPanel.add(abcLogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 240));

        pwLabel.setText("Password");
        loginPanel.add(pwLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 10));

        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        loginPanel.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 200, 30));
        loginPanel.add(pwTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 200, 30));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 90, 30));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setForeground(new java.awt.Color(0, 0, 51));

        homeMenu.setText("Home");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        homeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuActionPerformed(evt);
            }
        });
        menuBar.add(homeMenu);

        studentMenu.setText("Student");

        newStudent.setText("New");
        newStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentActionPerformed(evt);
            }
        });
        studentMenu.add(newStudent);

        updateStudent.setText("Update");
        updateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentActionPerformed(evt);
            }
        });
        studentMenu.add(updateStudent);

        enlistStudent.setText("Enlist");
        enlistStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enlistStudentActionPerformed(evt);
            }
        });
        studentMenu.add(enlistStudent);

        deleteStudent.setText("Delete");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });
        studentMenu.add(deleteStudent);

        showBalance.setText("Show balance");
        showBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBalanceActionPerformed(evt);
            }
        });
        studentMenu.add(showBalance);

        viewStudent.setText("View");
        viewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentActionPerformed(evt);
            }
        });
        studentMenu.add(viewStudent);

        menuBar.add(studentMenu);

        teacherMenu.setText("Faculty");

        newTeacher.setText("New");
        newTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTeacherActionPerformed(evt);
            }
        });
        teacherMenu.add(newTeacher);

        updateTeacher.setText("Update");
        updateTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherActionPerformed(evt);
            }
        });
        teacherMenu.add(updateTeacher);

        deleteTeacher.setText("Delete");
        deleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherActionPerformed(evt);
            }
        });
        teacherMenu.add(deleteTeacher);

        salaryTeacher.setText("Calculate salary");
        teacherMenu.add(salaryTeacher);

        viewTeacher.setText("View");
        viewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeacherActionPerformed(evt);
            }
        });
        teacherMenu.add(viewTeacher);

        menuBar.add(teacherMenu);

        helpMenu.setText("Help");
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        loginPanel.setVisible(false); 
        mainPanel.setVisible(true);
        homePanel.setVisible(true);
        menuBar.setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void newStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentActionPerformed
        setAllInvisible();
        addHeaderLabel.setText("New Student");
        newPanel.setVisible(true);
        choice = STUDENT;
    }//GEN-LAST:event_newStudentActionPerformed

    private void updateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentActionPerformed
        setAllInvisible();
        updateHeaderLabel.setText("Update Student");
        updatePanel.setVisible(true);
        choice = STUDENT;
    }//GEN-LAST:event_updateStudentActionPerformed

    private void showBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showBalanceActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        setAllInvisible();
        delLabel.setText("Delete Student");
        deletePanel.setVisible(true);   
        choice = STUDENT;
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void fnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTFActionPerformed

    private void genderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderCBActionPerformed

    private void fnameTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTF1ActionPerformed

    private void genderCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderCB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderCB1ActionPerformed

    private void homeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuActionPerformed
        
    }//GEN-LAST:event_homeMenuActionPerformed

    private void newTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTeacherActionPerformed
        setAllInvisible();
        addHeaderLabel.setText("New Teacher");
        newPanel.setVisible(true);
        choice = TEACHER;
    }//GEN-LAST:event_newTeacherActionPerformed

    private void updateTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherActionPerformed
        setAllInvisible();
        updateHeaderLabel.setText("Update Teacher");
        updatePanel.setVisible(true);
        choice = TEACHER;
    }//GEN-LAST:event_updateTeacherActionPerformed

    private void deleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherActionPerformed
        setAllInvisible();
        delLabel.setText("Delete Teacher");
        deletePanel.setVisible(true);        
        choice = TEACHER;
    }//GEN-LAST:event_deleteTeacherActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        if (choice == STUDENT) {
            
            Student student = new Student(fnameTF1.getText(),
                    lnameTF1.getText(),
                    genderCB1.getSelectedItem().toString(),
                    phoneTF1.getText(),
                    addressTF1.getText());
            if(student.addStudent()) {
                JOptionPane.showMessageDialog(this, "Added student: " + student.lastName.toUpperCase() + ", " + student.firstName);
                initNewFields();
            }            
            else {
                JOptionPane.showMessageDialog(this, "Cannot add student.");
                initNewFields();
            }
        }
        else {
            teacherDetailsFrame.setVisible(true);
            
        }
    }//GEN-LAST:event_newBtnActionPerformed

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        setAllInvisible();
        homePanel.setVisible(true);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void teacherDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherDetailsBtnActionPerformed
        Teacher teacher = new Teacher(fnameTF1.getText(),
                lnameTF1.getText(),
                genderCB1.getSelectedItem().toString(),
                phoneTF1.getText(),addressTF1.getText(),
                deptCB.getSelectedItem().toString(),
                desigCB.getSelectedItem().toString());
            
            if(teacher.addTeacher()) {
                JOptionPane.showMessageDialog(this, "Added teacher: " + teacher.lastName.toUpperCase() + ", " + teacher.firstName);
                initNewFields();
            }            
            else {
                JOptionPane.showMessageDialog(this, "Cannot add teacher.");
                initNewFields();
            }
            teacherDetailsFrame.dispose();
    }//GEN-LAST:event_teacherDetailsBtnActionPerformed

    private void delTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delTFActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int reply;
        String delname = "";
        
        if (choice == STUDENT) {            
            Student student = new Student();
            if (student.searchStudent(Integer.valueOf(delTF.getText()))) {
                delname = student.lastName.toUpperCase() + ", " + student.firstName; 
                reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + delname + "?",
                    "", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    if(student.delStudent()){
                        JOptionPane.showMessageDialog(this, "Deleted " + delname + " successfully.");
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Delete failed.");
                    }
                }
                else {
                   System.exit(0);
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "ID number does not exist.");
                delTF.setText("");
            }           
            
        }
        else {            
            Teacher teacher = new Teacher();
            if (teacher.searchTeacher(Integer.valueOf(delTF.getText()))) {
                delname = teacher.lastName.toUpperCase() + ", " + teacher.firstName; 
                reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + delname + "?",
                    "", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    if(teacher.delTeacher()){
                        JOptionPane.showMessageDialog(this, "Deleted " + delname + " successfully.");
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Delete failed.");
                    }
                }
                else {
                   System.exit(0);
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "ID number does not exist.");
                delTF.setText("");
            }  
            
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void updateSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSearchMouseClicked
        int genderIndex = 0;
        if (choice == STUDENT) {
            Student student = new Student();
            if (student.searchStudent(Integer.valueOf(updateID.getText()))) {
                if (student.gender == "M") genderIndex = 0; else genderIndex = 1;
                enableFields(true);                
                fnameTF.setText(student.firstName);
                lnameTF.setText(student.lastName);
                phoneTF.setText(student.phoneNumber);
                genderCB.setSelectedIndex(genderIndex);
                addressTF.setText(student.address);                
            }
            else {
                JOptionPane.showMessageDialog(this, "ID number does not exist.");
                updateID.setText("");
            } 
        }
        else {
            Teacher teacher = new Teacher();
            if (teacher.searchTeacher(Integer.valueOf(updateID.getText()))) {
                if (teacher.gender == "M") genderIndex = 0; else genderIndex = 1;
                enableFields(true);                
                fnameTF.setText(teacher.firstName);
                lnameTF.setText(teacher.lastName);
                phoneTF.setText(teacher.phoneNumber);
                genderCB.setSelectedIndex(genderIndex);
                addressTF.setText(teacher.address);                
            }
            else {
                JOptionPane.showMessageDialog(this, "ID number does not exist.");
                updateID.setText("");
            }  
        }
    }//GEN-LAST:event_updateSearchMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (choice == STUDENT){
            Student student = new Student(Integer.valueOf(updateID.getText()),
                    fnameTF.getText(),
                    lnameTF.getText(),
                    genderCB.getSelectedItem().toString(),
                    phoneTF.getText(),
                    addressTF.getText());
            student.updateStudent();
        }
        else {
            Teacher teacher = new Teacher(Integer.valueOf(updateID.getText()),
                    fnameTF.getText(),
                    lnameTF.getText(),
                    genderCB.getSelectedItem().toString(),
                    phoneTF.getText(),
                    addressTF.getText());
            teacher.updateTeacher();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCancelBtnActionPerformed
        initUpdateFields();
    }//GEN-LAST:event_updateCancelBtnActionPerformed

    private void viewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeacherActionPerformed
        setAllInvisible();
        Teacher teacher = new Teacher();
        teacherTable.setModel(DbUtils.resultSetToTableModel(teacher.getAllTeachers()));        
        viewTeacherPanel.setVisible(true);
    }//GEN-LAST:event_viewTeacherActionPerformed

    private void viewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentActionPerformed
        setAllInvisible();
        Student student = new Student();
        studentTable.setModel(DbUtils.resultSetToTableModel(student.getAllStudents()));        
        viewStudentPanel.setVisible(true);
    }//GEN-LAST:event_viewStudentActionPerformed

    private void enlistStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enlistStudentActionPerformed
        setAllInvisible();
        enlistPanel.setVisible(true);
    }//GEN-LAST:event_enlistStudentActionPerformed

    private void enlistIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enlistIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enlistIDActionPerformed

    private void enlistSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enlistSearchMouseClicked
        Student student = new Student();
        boolean enrolled = student.searchEnrolled(Integer.valueOf(enlistID.getText()));
        boolean exist = student.searchStudent(Integer.valueOf(enlistID.getText()));
        if(exist && !enrolled){
            nameEnlistLabel.setText(student.lastName.toUpperCase() + ", " + student.firstName);
            enlistPanel2.setVisible(true);
        } else if (exist && enrolled) {
            JOptionPane.showMessageDialog(this, "Student already enrolled.");
            enlistPanel2.setVisible(true);
            nameEnlistLabel.setText(student.lastName.toUpperCase() + ", " + student.firstName);
            repModuleSpinner.setValue(student.repModule);
            repModuleSpinner.setEnabled(false);
            newModuleSpinner.setValue(student.newModule);
            newModuleSpinner.setEnabled(false);
            tuitionLbl.setText(String.valueOf(student.tuition));
            depositTF.setText(String.valueOf(student.deposit));
            depositTF.setEnabled(false);
            enrollBtn.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Student id does not exist.");  
        }        
    }//GEN-LAST:event_enlistSearchMouseClicked

    private void depositTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositTFActionPerformed

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBtnActionPerformed
        int deposit = 0;
        deposit = Integer.valueOf(depositTF.getText());
        if (deposit < .2*tuition || deposit > tuition){
            depositTF.setText("");
            JOptionPane.showMessageDialog(this, "Invalid deposit amount."); 
        }
        else {
            Student student = new Student();
            if (student.enrollStudent(Integer.valueOf(enlistID.getText()),
                    (Integer)repModuleSpinner.getValue(),
                    (Integer)newModuleSpinner.getValue(),
                    tuition - deposit,
                    deposit,
                    tuition)) {
                JOptionPane.showMessageDialog(this, "Successfully enrolled.");
                initEnlistFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to enroll."); 
            }
        }
    }//GEN-LAST:event_enrollBtnActionPerformed

    private void repModuleSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_repModuleSpinnerStateChanged
        total = (Integer)repModuleSpinner.getValue() + (Integer)newModuleSpinner.getValue();
        if (total > 6) {
                JOptionPane.showMessageDialog(this, "Cannot exceed 6 modules.");
                repModuleSpinner.setValue((Integer)repModuleSpinner.getPreviousValue());
        }
        else {
            if ((Integer)repModuleSpinner.getValue() < 0) {
            repModuleSpinner.setValue(0);            
            } 
            else if ((Integer)repModuleSpinner.getValue() > 2) {
                newModuleSpinner.setEnabled(false);
                newModuleSpinner.setValue(0);                
                total = (Integer)repModuleSpinner.getValue();
            }
            else if ((Integer)repModuleSpinner.getValue() > 6) {
                repModuleSpinner.setValue(6);
                JOptionPane.showMessageDialog(this, "Cannot exceed 6 modules.");
            } else {
                newModuleSpinner.setEnabled(true);         
            }
        }
        updateTuition();        
    }//GEN-LAST:event_repModuleSpinnerStateChanged

    private void newModuleSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newModuleSpinnerStateChanged
        total = (Integer)repModuleSpinner.getValue() + (Integer)newModuleSpinner.getValue();
        if (total > 6) {
                JOptionPane.showMessageDialog(this, "Cannot exceed 6 modules.");
                newModuleSpinner.setValue((Integer)newModuleSpinner.getPreviousValue());
        }
        else {
            if ((Integer)newModuleSpinner.getValue() < 0) {
                newModuleSpinner.setValue(0);            
            } 
            
            else if ((Integer)newModuleSpinner.getValue() > 6) {
                newModuleSpinner.setValue(6);
                JOptionPane.showMessageDialog(this, "Cannot exceed 6 modules.");
            }
        }
        updateTuition();
    }//GEN-LAST:event_newModuleSpinnerStateChanged

    private void enlistIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enlistIDMouseClicked
        initEnlistFields();
    }//GEN-LAST:event_enlistIDMouseClicked

    private void withRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withRBActionPerformed
        Student student = new Student();
        studentTable.setModel(DbUtils.resultSetToTableModel(student.getWithBalance()));  
    }//GEN-LAST:event_withRBActionPerformed

    private void withoutRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withoutRBActionPerformed
        Student student = new Student();
        studentTable.setModel(DbUtils.resultSetToTableModel(student.getWithoutBalance()));  
    }//GEN-LAST:event_withoutRBActionPerformed

    private void allRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRBActionPerformed
        Student student = new Student();
        studentTable.setModel(DbUtils.resultSetToTableModel(student.getAllStudents()));  
    }//GEN-LAST:event_allRBActionPerformed
    
    private void updateTuition(){
        tuition = (Integer)repModuleSpinner.getValue() * 110 + (Integer)newModuleSpinner.getValue() * 525;
        tuitionLbl.setText(String.valueOf(tuition));
    }
    
    private void setAllInvisible() {
        homePanel.setVisible(false);
        updatePanel.setVisible(false);
        newPanel.setVisible(false);
        deletePanel.setVisible(false);
        viewStudentPanel.setVisible(false);
        viewTeacherPanel.setVisible(false);
        enlistPanel.setVisible(false);
        enlistPanel2.setVisible(false);
    }
    
    private void enableFields(Boolean b){
        updateID.setEnabled(b);
        fnameTF.setEnabled(b);
        lnameTF.setEnabled(b);
        phoneTF.setEnabled(b);
        genderCB.setEnabled(b);
        addressTF.setEnabled(b);
        updateBtn.setEnabled(b);
        updateCancelBtn.setEnabled(b);
        updateID.setEnabled(!b);
    }
    
    private void initNewFields(){
        fnameTF1.setText("");
        lnameTF1.setText("");
        phoneTF1.setText("");
        genderCB1.setSelectedIndex(0);
        addressTF1.setText("");
    }
    
    private void initUpdateFields(){
        updateID.setText("");
        fnameTF.setText("");
        lnameTF.setText("");
        phoneTF.setText("");
        genderCB.setSelectedIndex(0);
        addressTF.setText("");
    }
    
    private void initEnlistFields(){
        repModuleSpinner.setValue(0);
        repModuleSpinner.setEnabled(true);
        newModuleSpinner.setValue(0);
        newModuleSpinner.setEnabled(true);
        tuitionLbl.setText("");
        depositTF.setText("");
        depositTF.setEnabled(true);
        enrollBtn.setEnabled(true);
        nameEnlistLabel.setText("");
        enlistPanel2.setVisible(false);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbcGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbcGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbcGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbcGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbcGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abcLogoLogin;
    private javax.swing.JLabel addHeaderLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField addressTF1;
    private javax.swing.JRadioButton allRB;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel delLabel;
    private javax.swing.JLabel delLabel1;
    private javax.swing.JTextField delTF;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JMenuItem deleteStudent;
    private javax.swing.JMenuItem deleteTeacher;
    private javax.swing.JTextField depositTF;
    private javax.swing.JComboBox<String> deptCB;
    private javax.swing.JComboBox<String> desigCB;
    private javax.swing.JTextField enlistID;
    private javax.swing.JPanel enlistPanel;
    private javax.swing.JPanel enlistPanel2;
    private javax.swing.JLabel enlistSearch;
    private javax.swing.JMenuItem enlistStudent;
    private javax.swing.JButton enrollBtn;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JTextField fnameTF1;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JComboBox<String> genderCB1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JTextField lnameTF1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoHome;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nameEnlistLabel;
    private javax.swing.JButton newBtn;
    private javax.swing.JSpinner newModuleSpinner;
    private javax.swing.JPanel newPanel;
    private javax.swing.JMenuItem newStudent;
    private javax.swing.JMenuItem newTeacher;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JTextField phoneTF1;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JPasswordField pwTF;
    private javax.swing.JSpinner repModuleSpinner;
    private javax.swing.JMenuItem salaryTeacher;
    private javax.swing.JMenuItem showBalance;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JTable studentTable;
    private javax.swing.ButtonGroup studentViewBG;
    private javax.swing.JButton teacherDetailsBtn;
    private javax.swing.JInternalFrame teacherDetailsFrame;
    private javax.swing.JLabel teacherDetailsName;
    private javax.swing.JMenu teacherMenu;
    private javax.swing.JTable teacherTable;
    private javax.swing.JLabel tuitionLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateCancelBtn;
    private javax.swing.JLabel updateHeaderLabel;
    private javax.swing.JTextField updateID;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JLabel updateSearch;
    private javax.swing.JMenuItem updateStudent;
    private javax.swing.JMenuItem updateTeacher;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTF;
    private javax.swing.JMenuItem viewStudent;
    private javax.swing.JLabel viewStudentLabel;
    private javax.swing.JPanel viewStudentPanel;
    private javax.swing.JMenuItem viewTeacher;
    private javax.swing.JLabel viewTeacherLabel;
    private javax.swing.JPanel viewTeacherPanel;
    private javax.swing.JRadioButton withRB;
    private javax.swing.JRadioButton withoutRB;
    // End of variables declaration//GEN-END:variables
}
